{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugboard-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bugboard.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bugboard.selectorLabels" . | nindent 6 }}
      app: postgres
  template:
    metadata:
      labels:
        {{- include "bugboard.selectorLabels" . | nindent 8 }}
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: bugboard-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: bugboard-postgres-pvc
{{- end -}}
