global:
  namespace: bugboard

backend:
  replicaCount: 2
  image:
    repository: ghcr.io/auxid-01/devops_project/backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  env:
    DATABASE_URL: postgresql://bugboard_user:password123@bugboard-postgres:5432/bugboard_db
    UPLOAD_DIR: /app/uploads
    CORS_ORIGINS: "*"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/auxid-01/devops_project/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

postgres:
  enabled: true
  image: postgres:16-alpine
  persistence:
    storage: 1Gi
  credentials:
    username: bugboard_user
    database: bugboard_db
    password: password123
  service:
    port: 5432

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
